package com.miempresa.erp.domain;

import static com.miempresa.erp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SubscriptionPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanAllPropertiesEquals(SubscriptionPlan expected, SubscriptionPlan actual) {
        assertSubscriptionPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertSubscriptionPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanAllUpdatablePropertiesEquals(SubscriptionPlan expected, SubscriptionPlan actual) {
        assertSubscriptionPlanUpdatableFieldsEquals(expected, actual);
        assertSubscriptionPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanAutoGeneratedPropertiesEquals(SubscriptionPlan expected, SubscriptionPlan actual) {
        assertThat(actual)
            .as("Verify SubscriptionPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanUpdatableFieldsEquals(SubscriptionPlan expected, SubscriptionPlan actual) {
        assertThat(actual)
            .as("Verify SubscriptionPlan relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getMonthlyPrice())
                    .as("check monthlyPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyPrice())
            )
            .satisfies(a ->
                assertThat(a.getAnnualPrice())
                    .as("check annualPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAnnualPrice())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanUpdatableRelationshipsEquals(SubscriptionPlan expected, SubscriptionPlan actual) {
        // empty method
    }
}
