apiVersion: v1
kind: Service
metadata:
  name: erp-microservice-nodeport
  namespace: bi-system
spec:
  type: NodePort
  ports:
  - port: 8001        
    targetPort: 8001  
    nodePort: 30002   
    protocol: TCP
  selector:
    app: erp-microservice  